language: r
r: 
  - oldrel
  - release
  - devel
  - bioc-release
  - bioc-devel
sudo: required
warnings_are_errors: true

bioc_packages:
  - BiocInstaller
  - AnnotationDbi
  - biomaRt
  - BiocGenerics
  - Biostrings
  - GenomicFeatures
  - GenomicRanges
  - Rsamtools

after_success:
  - Rscript -e 'library(covr);codecov()'
